### ISSUE TITLE
Validate that timestamps are POSIX

### ISSUE THREAD

**Issue by oobrien** [PierrickP/gbfs-validator#4]
Per GBFS spec, last_updated timestamps need to be POSIX timestamp format (i.e. no of seconds since 1 Jan 1970 UTC). A range-based check would make sure that the time is sensible (e.g. no of seconds rather than no of milliseconds).

**Comment by PierrickP** [comment]
@oobrien thank you.
I made a https://github.com/PierrickP/gbfs-validator/pull/5 to enforce this rule. Can you review it ?

**Comment by oobrien** [comment]
Thanks, yes that's great.
